name: Build CarpetPlugin Jar
on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Give gradlew execute permission
        run: chmod +x ./gradlew || true
      - name: Build (tries shadowJar then jar)
        run: |
          ./gradlew clean shadowJar || ./gradlew clean build || ./gradlew clean jar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: carpetplugin-jar
          path: |
            **/build/libs/*.jar
